// 核文法 (大単元1〜14) の公開問題バンク。
// 出題項目の配列は公開教材・公的資料を参照し、設問文・選択肢・解説は新規作成。
// 収録方針とライセンスは ../sources.ts を参照。

import type { PublicGrammarQuestion } from './types';

const WB = 'cc-by-digital-workbook-esol';
const AA = 'cc-by-advanced-academic-grammar';
const PD = 'pd-1001-questions';

export const CORE_QUESTIONS: PublicGrammarQuestion[] = [
  // ---- 文の種類と語順 ----
  {
    id: 'pg-sentence-kinds-1', nodeId: 'sentence-kinds',
    sentence: '___ a wonderful view this is!',
    choices: ['What', 'How', 'Which', 'That'], correctIndex: 0,
    explanation: '感嘆文で〈冠詞+名詞〉が続くときは What を使う。形容詞・副詞だけが続くときは How。',
    sentenceJa: 'なんて素晴らしい眺めなんだろう。', sourceId: PD,
  },
  {
    id: 'pg-sentence-kinds-2', nodeId: 'sentence-kinds',
    sentence: '___ be late for the meeting tomorrow.',
    choices: ["Don't", 'Not', 'No', 'Never to'], correctIndex: 0,
    explanation: '否定の命令文は Don\'t + 動詞の原形。主語を置かない点に注意。',
    sentenceJa: '明日の会議に遅れないように。', sourceId: WB,
  },
  {
    id: 'pg-sentence-order-1', nodeId: 'sentence-order',
    sentence: '___ a lot of books on the shelf.',
    choices: ['There are', 'There is', 'It is', 'They are'], correctIndex: 0,
    explanation: 'there is/are 構文では、be動詞は後ろの名詞に一致する。books は複数なので are。',
    sentenceJa: '棚にはたくさんの本がある。', sourceId: WB,
  },
  {
    id: 'pg-sentence-order-2', nodeId: 'sentence-order',
    sentence: 'She speaks ___ to make herself understood.',
    choices: ['clearly enough', 'enough clearly', 'clear enough', 'enough clear'], correctIndex: 0,
    explanation: 'enough は形容詞・副詞を修飾するとき、必ずその後ろに置く。動詞を修飾するので副詞 clearly。',
    sentenceJa: '彼女は自分の意図が伝わるくらい明瞭に話す。', sourceId: AA,
  },
  {
    id: 'pg-sentence-patterns-1', nodeId: 'sentence-patterns',
    sentence: 'The soup ___ delicious.',
    choices: ['tastes', 'tastes to', 'is tasted', 'tastes like delicious'], correctIndex: 0,
    explanation: 'taste は SVC をとる感覚動詞で、補語には形容詞が来る（第2文型）。',
    sentenceJa: 'そのスープはおいしい味がする。', sourceId: PD,
  },
  {
    id: 'pg-sentence-patterns-2', nodeId: 'sentence-patterns',
    sentence: 'It is important ___ the deadline.',
    choices: ['to meet', 'meeting', 'meet', 'met'], correctIndex: 0,
    explanation: 'It は形式主語で、真主語は to 不定詞。It is 形容詞 to do の形。',
    sentenceJa: '締め切りを守ることが重要だ。', sourceId: AA,
  },

  // ---- 動詞と時制 ----
  {
    id: 'pg-tense-basic-1', nodeId: 'tense-basic',
    sentence: 'Water ___ at 100 degrees Celsius.',
    choices: ['boils', 'is boiling', 'boiled', 'has boiled'], correctIndex: 0,
    explanation: '不変の真理・一般的事実は現在形で表す。',
    sentenceJa: '水は摂氏100度で沸騰する。', sourceId: WB,
  },
  {
    id: 'pg-tense-basic-2', nodeId: 'tense-basic',
    sentence: 'Listen! Someone ___ the piano next door.',
    choices: ['is playing', 'plays', 'played', 'has played'], correctIndex: 0,
    explanation: '今この瞬間に進行中の動作は現在進行形。Listen! が今の場面を示している。',
    sentenceJa: '聞いて。隣で誰かがピアノを弾いている。', sourceId: WB,
  },
  {
    id: 'pg-tense-future-1', nodeId: 'tense-future',
    sentence: 'Look at those clouds. It ___ rain soon.',
    choices: ['is going to', 'will have', 'would', 'is'], correctIndex: 0,
    explanation: '目の前の状況を根拠にした予測は be going to が自然。',
    sentenceJa: 'あの雲を見て。もうすぐ雨が降りそうだ。', sourceId: WB,
  },
  {
    id: 'pg-tense-future-2', nodeId: 'tense-future',
    sentence: 'The train ___ at seven tomorrow morning.',
    choices: ['leaves', 'is leaving to', 'will be left', 'leave'], correctIndex: 0,
    explanation: '時刻表など確定した予定は現在形で未来を表せる。',
    sentenceJa: 'その列車は明日の朝7時に出発する。', sourceId: AA,
  },
  {
    id: 'pg-tense-agreement-1', nodeId: 'tense-agreement',
    sentence: 'I will call you when he ___ back.',
    choices: ['comes', 'will come', 'will have come', 'came'], correctIndex: 0,
    explanation: '時・条件を表す副詞節の中では、未来のことでも現在形を使う。',
    sentenceJa: '彼が戻ってきたら電話します。', sourceId: AA,
  },
  {
    id: 'pg-tense-agreement-2', nodeId: 'tense-agreement',
    sentence: 'She said that she ___ tired.',
    choices: ['was', 'is', 'has been', 'will be'], correctIndex: 0,
    explanation: '主節が過去形なら従属節も過去にずらす（時制の一致）。',
    sentenceJa: '彼女は疲れていると言った。', sourceId: PD,
  },

  // ---- 完了形 ----
  {
    id: 'pg-perfect-present-1', nodeId: 'perfect-present',
    sentence: 'I ___ in this town for ten years.',
    choices: ['have lived', 'live', 'lived', 'am living'], correctIndex: 0,
    explanation: 'for + 期間を伴い、過去から現在まで続く状態は現在完了（継続）。',
    sentenceJa: '私はこの町に10年間住んでいる。', sourceId: WB,
  },
  {
    id: 'pg-perfect-present-2', nodeId: 'perfect-present',
    sentence: 'I ___ my homework, so I can go out now.',
    choices: ['have finished', 'finish', 'am finishing', 'had finished'], correctIndex: 0,
    explanation: '完了した動作が現在に結果として影響している場合は現在完了（完了・結果）。',
    sentenceJa: '宿題を終えたので、今から出かけられる。', sourceId: WB,
  },
  {
    id: 'pg-perfect-past-1', nodeId: 'perfect-past',
    sentence: 'When I arrived, the train ___ already left.',
    choices: ['had', 'has', 'was', 'would'], correctIndex: 0,
    explanation: '過去のある時点より前に完了していた事柄は過去完了（大過去）。',
    sentenceJa: '私が着いたとき、列車はすでに出発していた。', sourceId: AA,
  },
  {
    id: 'pg-perfect-past-2', nodeId: 'perfect-past',
    sentence: 'She lost the watch her father ___ her.',
    choices: ['had given', 'has given', 'gives', 'give'], correctIndex: 0,
    explanation: '「なくした」より前の出来事なので過去完了で時間の前後を示す。',
    sentenceJa: '彼女は父がくれた時計をなくした。', sourceId: PD,
  },
  {
    id: 'pg-perfect-future-1', nodeId: 'perfect-future',
    sentence: 'By next April, I ___ here for three years.',
    choices: ['will have worked', 'will work', 'have worked', 'worked'], correctIndex: 0,
    explanation: 'by + 未来の時点までの継続は未来完了 will have p.p.。',
    sentenceJa: '来年の4月で、私はここで3年働いたことになる。', sourceId: AA,
  },
  {
    id: 'pg-perfect-future-2', nodeId: 'perfect-future',
    sentence: 'They ___ for two hours when the bus finally came.',
    choices: ['had been waiting', 'have waited', 'are waiting', 'will wait'], correctIndex: 0,
    explanation: '過去のある時点まで続いていた動作は過去完了進行形。',
    sentenceJa: 'バスがようやく来たとき、彼らは2時間待ち続けていた。', sourceId: AA,
  },

  // ---- 助動詞 ----
  {
    id: 'pg-modal-basic-1', nodeId: 'modal-basic',
    sentence: 'You ___ be tired after such a long trip.',
    choices: ['must', 'can', 'should have', 'ought'], correctIndex: 0,
    explanation: 'must には「〜にちがいない」という強い推量の意味がある。',
    sentenceJa: 'あんなに長い旅の後だから、あなたは疲れているにちがいない。', sourceId: WB,
  },
  {
    id: 'pg-modal-basic-2', nodeId: 'modal-basic',
    sentence: 'You ___ not enter this room without permission.',
    choices: ['may', 'need', 'dare', 'used'], correctIndex: 0,
    explanation: 'may not は「〜してはいけない」という不許可を表す。',
    sentenceJa: '許可なくこの部屋に入ってはいけません。', sourceId: PD,
  },
  {
    id: 'pg-modal-will-1', nodeId: 'modal-will',
    sentence: 'There ___ a post office here, but it closed last year.',
    choices: ['used to be', 'would be', 'is used to be', 'was used to be'], correctIndex: 0,
    explanation: 'used to は「以前は〜だった」という過去の状態・習慣を表す。後ろは動詞の原形。',
    sentenceJa: '以前はここに郵便局があったが、昨年閉まった。', sourceId: AA,
  },
  {
    id: 'pg-modal-will-2', nodeId: 'modal-will',
    sentence: 'When we were children, we ___ often go fishing together.',
    choices: ['would', 'used', 'will', 'could have'], correctIndex: 0,
    explanation: 'would には「よく〜したものだ」という過去の反復動作の意味がある。',
    sentenceJa: '子どもの頃、私たちはよく一緒に釣りに行ったものだ。', sourceId: AA,
  },
  {
    id: 'pg-modal-perfect-1', nodeId: 'modal-perfect',
    sentence: 'He ___ have missed the train; he is never late.',
    choices: ['cannot', 'must', 'should', 'need not'], correctIndex: 0,
    explanation: 'cannot have p.p. は「〜したはずがない」という過去への強い否定的推量。',
    sentenceJa: '彼が電車に乗り遅れたはずがない。決して遅れない人だ。', sourceId: AA,
  },
  {
    id: 'pg-modal-perfect-2', nodeId: 'modal-perfect',
    sentence: 'You ___ have told me earlier. I could have helped you.',
    choices: ['should', 'must', 'would', 'can'], correctIndex: 0,
    explanation: 'should have p.p. は「〜すべきだったのに（しなかった）」という後悔・非難。',
    sentenceJa: 'もっと早く言ってくれればよかったのに。手伝えたのに。', sourceId: AA,
  },
  {
    id: 'pg-modal-idiom-1', nodeId: 'modal-idiom',
    sentence: 'You ___ see a doctor right away.',
    choices: ['had better', 'had better to', 'would better', 'have better'], correctIndex: 0,
    explanation: 'had better + 動詞の原形で「〜した方がよい」。to は付かない。',
    sentenceJa: 'すぐに医者に診てもらった方がいい。', sourceId: PD,
  },
  {
    id: 'pg-modal-idiom-2', nodeId: 'modal-idiom',
    sentence: 'The committee insisted that the plan ___ revised.',
    choices: ['be', 'is', 'was', 'has been'], correctIndex: 0,
    explanation: '要求・提案・主張を表す動詞に続く that 節は〈(should) + 原形〉になる。',
    sentenceJa: '委員会はその計画を修正するよう主張した。', sourceId: AA,
  },

  // ---- 態 ----
  {
    id: 'pg-voice-basic-1', nodeId: 'voice-basic',
    sentence: 'This bridge ___ fifty years ago.',
    choices: ['was built', 'built', 'has built', 'is building'], correctIndex: 0,
    explanation: '主語が動作を受ける側なので受動態 be + p.p.。過去の時点なので was built。',
    sentenceJa: 'この橋は50年前に建設された。', sourceId: WB,
  },
  {
    id: 'pg-voice-basic-2', nodeId: 'voice-basic',
    sentence: 'The mountain ___ covered with snow all year round.',
    choices: ['is', 'has', 'does', 'was being'], correctIndex: 0,
    explanation: 'be covered with は「〜で覆われている」。by 以外の前置詞をとる受動態の代表例。',
    sentenceJa: 'その山は一年中雪で覆われている。', sourceId: AA,
  },
  {
    id: 'pg-voice-various-1', nodeId: 'voice-various',
    sentence: 'The road ___ repaired at the moment.',
    choices: ['is being', 'is', 'has', 'was been'], correctIndex: 0,
    explanation: '進行形の受動態は be being + p.p.。',
    sentenceJa: 'その道路は今まさに修理されているところだ。', sourceId: AA,
  },
  {
    id: 'pg-voice-various-2', nodeId: 'voice-various',
    sentence: 'The report must ___ by Friday.',
    choices: ['be submitted', 'submit', 'been submitted', 'be submitting'], correctIndex: 0,
    explanation: '助動詞を伴う受動態は〈助動詞 + be + p.p.〉。',
    sentenceJa: 'その報告書は金曜までに提出されなければならない。', sourceId: AA,
  },
  {
    id: 'pg-voice-order-1', nodeId: 'voice-order',
    sentence: 'I ___ a beautiful bouquet by my colleagues.',
    choices: ['was given', 'was gave', 'gave', 'was given to'], correctIndex: 0,
    explanation: 'SVOO の受動態。人を主語にすると〈be given + 物〉の語順になる。',
    sentenceJa: '私は同僚たちから美しい花束をもらった。', sourceId: PD,
  },
  {
    id: 'pg-voice-order-2', nodeId: 'voice-order',
    sentence: 'The child ___ care of by his grandmother.',
    choices: ['was taken', 'was taken the', 'took', 'was took'], correctIndex: 0,
    explanation: '群動詞 take care of を受動態にするとき、of を落とさずひとかたまりで扱う。',
    sentenceJa: 'その子は祖母に世話をされていた。', sourceId: PD,
  },

  // ---- 不定詞 ----
  {
    id: 'pg-infinitive-three-1', nodeId: 'infinitive-three',
    sentence: 'My dream is ___ abroad someday.',
    choices: ['to study', 'study', 'studied', 'studies'], correctIndex: 0,
    explanation: '補語になる名詞的用法の不定詞。「〜すること」の意味。',
    sentenceJa: '私の夢はいつか留学することだ。', sourceId: WB,
  },
  {
    id: 'pg-infinitive-three-2', nodeId: 'infinitive-three',
    sentence: 'She has a lot of work ___ today.',
    choices: ['to finish', 'finishing', 'finished to', 'finish'], correctIndex: 0,
    explanation: '前の名詞 work を修飾する形容詞的用法の不定詞。',
    sentenceJa: '彼女には今日終わらせるべき仕事がたくさんある。', sourceId: AA,
  },
  {
    id: 'pg-infinitive-subject-1', nodeId: 'infinitive-subject',
    sentence: 'It is difficult ___ to solve this problem alone.',
    choices: ['for him', 'of him', 'to him', 'that he'], correctIndex: 0,
    explanation: '不定詞の意味上の主語は原則 for + 人。人の性質を表す形容詞のときだけ of + 人。',
    sentenceJa: '彼が一人でこの問題を解くのは難しい。', sourceId: AA,
  },
  {
    id: 'pg-infinitive-subject-2', nodeId: 'infinitive-subject',
    sentence: 'He seems ___ rich when he was young.',
    choices: ['to have been', 'to be', 'being', 'have been'], correctIndex: 0,
    explanation: '主節より前の時を表すときは完了不定詞 to have p.p.。',
    sentenceJa: '彼は若い頃は裕福だったようだ。', sourceId: AA,
  },
  {
    id: 'pg-infinitive-bare-1', nodeId: 'infinitive-bare',
    sentence: 'The teacher made the students ___ the passage aloud.',
    choices: ['read', 'to read', 'reading', 'to reading'], correctIndex: 0,
    explanation: '使役動詞 make は〈make + O + 動詞の原形〉をとる。',
    sentenceJa: '先生は生徒たちにその一節を音読させた。', sourceId: PD,
  },
  {
    id: 'pg-infinitive-bare-2', nodeId: 'infinitive-bare',
    sentence: 'I saw him ___ the building around noon.',
    choices: ['enter', 'to enter', 'entered', 'to entering'], correctIndex: 0,
    explanation: '知覚動詞 see は〈see + O + 原形〉で動作の一部始終を見たことを表す。',
    sentenceJa: '正午ごろ、彼がその建物に入るのを見た。', sourceId: PD,
  },
  {
    id: 'pg-infinitive-construction-1', nodeId: 'infinitive-construction',
    sentence: 'This box is ___ heavy for me to carry.',
    choices: ['too', 'so', 'very', 'enough'], correctIndex: 0,
    explanation: 'too ~ to do は「あまりに〜なので…できない」。',
    sentenceJa: 'この箱は重すぎて私には運べない。', sourceId: WB,
  },
  {
    id: 'pg-infinitive-construction-2', nodeId: 'infinitive-construction',
    sentence: 'He worked hard ___ to pass the exam.',
    choices: ['so as', 'so that', 'in order', 'such as'], correctIndex: 0,
    explanation: 'so as to do は「〜するために」という目的を表す。',
    sentenceJa: '彼は試験に合格するために一生懸命勉強した。', sourceId: AA,
  },

  // ---- 動名詞 ----
  {
    id: 'pg-gerund-basic-1', nodeId: 'gerund-basic',
    sentence: '___ early is good for your health.',
    choices: ['Getting up', 'Get up', 'To getting up', 'Got up'], correctIndex: 0,
    explanation: '主語になる動名詞。「〜すること」を表し、単数扱い。',
    sentenceJa: '早起きは健康に良い。', sourceId: WB,
  },
  {
    id: 'pg-gerund-basic-2', nodeId: 'gerund-basic',
    sentence: 'I am looking forward to ___ from you.',
    choices: ['hearing', 'hear', 'be heard', 'have heard'], correctIndex: 0,
    explanation: 'look forward to の to は前置詞なので、後ろは動名詞。',
    sentenceJa: 'お便りをお待ちしています。', sourceId: AA,
  },
  {
    id: 'pg-gerund-subject-1', nodeId: 'gerund-subject',
    sentence: 'I don\'t mind ___ waiting for a while.',
    choices: ['his', 'he', 'him to', 'that he'], correctIndex: 0,
    explanation: '動名詞の意味上の主語は所有格または目的格で示す。',
    sentenceJa: '彼がしばらく待つことは気にならない。', sourceId: PD,
  },
  {
    id: 'pg-gerund-subject-2', nodeId: 'gerund-subject',
    sentence: 'She is proud of ___ won the first prize.',
    choices: ['having', 'have', 'to have', 'being'], correctIndex: 0,
    explanation: '主節より前の時を表す動名詞は完了動名詞 having p.p.。',
    sentenceJa: '彼女は一等賞を取ったことを誇りに思っている。', sourceId: AA,
  },
  {
    id: 'pg-gerund-vs-infinitive-1', nodeId: 'gerund-vs-infinitive',
    sentence: 'Remember ___ the door when you leave.',
    choices: ['to lock', 'locking', 'locked', 'to locking'], correctIndex: 0,
    explanation: 'remember to do は「これから〜するのを忘れない」、remember doing は「〜したのを覚えている」。',
    sentenceJa: '出るときにドアに鍵をかけるのを忘れないで。', sourceId: AA,
  },
  {
    id: 'pg-gerund-vs-infinitive-2', nodeId: 'gerund-vs-infinitive',
    sentence: 'He finally gave up ___ to convince her.',
    choices: ['trying', 'to try', 'try', 'tried'], correctIndex: 0,
    explanation: 'give up は動名詞のみを目的語にとる。',
    sentenceJa: '彼はついに彼女を説得しようとするのをあきらめた。', sourceId: PD,
  },

  // ---- 分詞 ----
  {
    id: 'pg-participle-use-1', nodeId: 'participle-use',
    sentence: 'The news was so ___ that we could not believe it.',
    choices: ['surprising', 'surprised', 'surprise', 'to surprise'], correctIndex: 0,
    explanation: '「（人を）驚かせるような」は現在分詞。人が驚く側なら surprised。',
    sentenceJa: 'その知らせはとても驚くべきもので、私たちは信じられなかった。', sourceId: WB,
  },
  {
    id: 'pg-participle-use-2', nodeId: 'participle-use',
    sentence: 'Look at the house ___ on the hill.',
    choices: ['standing', 'stood', 'to stand', 'stands'], correctIndex: 0,
    explanation: '後ろから名詞を修飾する現在分詞。house が「立っている」側なので能動。',
    sentenceJa: '丘の上に立っているあの家を見て。', sourceId: PD,
  },
  {
    id: 'pg-participle-construction-1', nodeId: 'participle-construction',
    sentence: '___ what to say, he remained silent.',
    choices: ['Not knowing', 'Not known', 'Knowing not', 'Not to know'], correctIndex: 0,
    explanation: '分詞構文の否定は not を分詞の前に置く。',
    sentenceJa: '何と言えばよいか分からず、彼は黙ったままだった。', sourceId: AA,
  },
  {
    id: 'pg-participle-construction-2', nodeId: 'participle-construction',
    sentence: '___ finished his work, he went out for a walk.',
    choices: ['Having', 'Have', 'Being', 'To have'], correctIndex: 0,
    explanation: '主節より前に完了した動作を表す分詞構文は Having p.p.。',
    sentenceJa: '仕事を終えてから、彼は散歩に出かけた。', sourceId: AA,
  },
  {
    id: 'pg-participle-with-1', nodeId: 'participle-with',
    sentence: 'He was listening to me with his arms ___.',
    choices: ['folded', 'folding', 'to fold', 'fold'], correctIndex: 0,
    explanation: '付帯状況の with + O + 分詞。腕は「組まれる」側なので過去分詞。',
    sentenceJa: '彼は腕を組んで私の話を聞いていた。', sourceId: AA,
  },
  {
    id: 'pg-participle-with-2', nodeId: 'participle-with',
    sentence: "Don't keep me ___ so long.",
    choices: ['waiting', 'to wait', 'waited', 'wait'], correctIndex: 0,
    explanation: 'keep + O + doing で「Oを〜させ続ける」。',
    sentenceJa: 'そんなに長く私を待たせないで。', sourceId: PD,
  },

  // ---- 比較 ----
  {
    id: 'pg-comparison-positive-1', nodeId: 'comparison-positive',
    sentence: 'This book is not ___ interesting as that one.',
    choices: ['so', 'more', 'as much', 'very'], correctIndex: 0,
    explanation: '否定の原級比較では not so ~ as が使える（not as ~ as も可）。',
    sentenceJa: 'この本はあの本ほど面白くない。', sourceId: WB,
  },
  {
    id: 'pg-comparison-positive-2', nodeId: 'comparison-positive',
    sentence: 'Please come ___ soon as possible.',
    choices: ['as', 'so', 'more', 'the'], correctIndex: 0,
    explanation: 'as ~ as possible で「できるだけ〜」。',
    sentenceJa: 'できるだけ早く来てください。', sourceId: WB,
  },
  {
    id: 'pg-comparison-comparative-1', nodeId: 'comparison-comparative',
    sentence: '___ you exercise, the healthier you will become.',
    choices: ['The more', 'More', 'The most', 'As more'], correctIndex: 0,
    explanation: 'the 比較級 ~, the 比較級 ... で「〜すればするほど…」。',
    sentenceJa: '運動すればするほど健康になる。', sourceId: AA,
  },
  {
    id: 'pg-comparison-comparative-2', nodeId: 'comparison-comparative',
    sentence: 'This is ___ the best restaurant in town.',
    choices: ['by far', 'very', 'much more', 'so'], correctIndex: 0,
    explanation: 'by far は最上級を強調する。very は〈the very + 最上級〉の語順で使う。',
    sentenceJa: 'ここは断然この町で一番のレストランだ。', sourceId: AA,
  },
  {
    id: 'pg-comparison-idiom-1', nodeId: 'comparison-idiom',
    sentence: 'This room is ___ as large as that one.',
    choices: ['twice', 'two times more', 'double', 'twofold'], correctIndex: 0,
    explanation: '倍数表現は〈倍数 + as 原級 as〉。2倍は twice。',
    sentenceJa: 'この部屋はあの部屋の2倍の広さだ。', sourceId: PD,
  },
  {
    id: 'pg-comparison-idiom-2', nodeId: 'comparison-idiom',
    sentence: 'He is ___ more than a beginner at chess.',
    choices: ['no', 'not', 'much', 'far'], correctIndex: 0,
    explanation: 'no more than は「〜にすぎない」。not more than なら「多くても」。',
    sentenceJa: '彼はチェスでは初心者にすぎない。', sourceId: PD,
  },

  // ---- 関係詞 ----
  {
    id: 'pg-relative-pronoun-1', nodeId: 'relative-pronoun',
    sentence: 'I know a boy ___ father is a famous pianist.',
    choices: ['whose', 'who', 'which', 'whom'], correctIndex: 0,
    explanation: '後ろの名詞 father との所有関係を示すので所有格の関係代名詞 whose。',
    sentenceJa: '私は父親が有名なピアニストである少年を知っている。', sourceId: PD,
  },
  {
    id: 'pg-relative-pronoun-2', nodeId: 'relative-pronoun',
    sentence: 'This is the camera ___ I bought last week.',
    choices: ['which', 'who', 'whose', 'what'], correctIndex: 0,
    explanation: '先行詞が物で、関係詞節内で目的語の働きをするので which（that も可）。',
    sentenceJa: 'これが先週買ったカメラです。', sourceId: WB,
  },
  {
    id: 'pg-relative-preposition-1', nodeId: 'relative-preposition',
    sentence: 'This is the house ___ which he was born.',
    choices: ['in', 'on', 'at', 'to'], correctIndex: 0,
    explanation: '前置詞 + 関係代名詞。be born in the house の in が前に出た形。',
    sentenceJa: 'これが彼の生まれた家だ。', sourceId: AA,
  },
  {
    id: 'pg-relative-preposition-2', nodeId: 'relative-preposition',
    sentence: 'He failed the exam, ___ surprised everyone.',
    choices: ['which', 'that', 'what', 'it'], correctIndex: 0,
    explanation: '前の文全体を先行詞にする非制限用法の which。that は非制限用法では使えない。',
    sentenceJa: '彼は試験に落ちたが、それは皆を驚かせた。', sourceId: AA,
  },
  {
    id: 'pg-relative-adverb-1', nodeId: 'relative-adverb',
    sentence: 'I remember the day ___ we first met.',
    choices: ['when', 'which', 'what', 'where'], correctIndex: 0,
    explanation: '先行詞が時を表す語で、節内が完全な文なので関係副詞 when。',
    sentenceJa: '私は私たちが初めて会った日を覚えている。', sourceId: WB,
  },
  {
    id: 'pg-relative-adverb-2', nodeId: 'relative-adverb',
    sentence: 'That is the reason ___ he was absent.',
    choices: ['why', 'which', 'how', 'what'], correctIndex: 0,
    explanation: '先行詞が the reason のときの関係副詞は why。',
    sentenceJa: 'それが彼が欠席した理由だ。', sourceId: PD,
  },
  {
    id: 'pg-relative-compound-1', nodeId: 'relative-compound',
    sentence: '___ he says, I will not change my mind.',
    choices: ['Whatever', 'However', 'Whichever', 'Whenever'], correctIndex: 0,
    explanation: '複合関係代名詞 whatever は譲歩で「何を〜しても」。',
    sentenceJa: '彼が何と言おうと、私は考えを変えない。', sourceId: AA,
  },
  {
    id: 'pg-relative-compound-2', nodeId: 'relative-compound',
    sentence: '___ he said was completely true.',
    choices: ['What', 'That', 'Which', 'Whose'], correctIndex: 0,
    explanation: '関係代名詞 what は先行詞を含み「〜すること・もの」の名詞節を作る。',
    sentenceJa: '彼が言ったことは完全に真実だった。', sourceId: PD,
  },

  // ---- 仮定法 ----
  {
    id: 'pg-subjunctive-if-1', nodeId: 'subjunctive-if',
    sentence: 'If I ___ you, I would accept the offer.',
    choices: ['were', 'am', 'will be', 'had been'], correctIndex: 0,
    explanation: '現在の事実に反する仮定は仮定法過去。be動詞は人称にかかわらず were が原則。',
    sentenceJa: 'もし私があなたなら、その申し出を受けるだろう。', sourceId: AA,
  },
  {
    id: 'pg-subjunctive-if-2', nodeId: 'subjunctive-if',
    sentence: 'If he ___ harder, he would have passed the exam.',
    choices: ['had studied', 'studied', 'has studied', 'studies'], correctIndex: 0,
    explanation: '過去の事実に反する仮定は仮定法過去完了〈if S had p.p., S would have p.p.〉。',
    sentenceJa: 'もっと熱心に勉強していたら、彼は試験に合格していただろう。', sourceId: AA,
  },
  {
    id: 'pg-subjunctive-wish-1', nodeId: 'subjunctive-wish',
    sentence: 'I wish I ___ speak French fluently.',
    choices: ['could', 'can', 'will be able to', 'may'], correctIndex: 0,
    explanation: '現在の願望を表す I wish の後ろは仮定法過去。',
    sentenceJa: 'フランス語を流暢に話せたらいいのに。', sourceId: WB,
  },
  {
    id: 'pg-subjunctive-wish-2', nodeId: 'subjunctive-wish',
    sentence: 'He talks ___ he knew everything about it.',
    choices: ['as if', 'even if', 'as', 'so that'], correctIndex: 0,
    explanation: 'as if + 仮定法過去で「まるで〜であるかのように」。',
    sentenceJa: '彼はまるでそれについて何でも知っているかのように話す。', sourceId: AA,
  },
  {
    id: 'pg-subjunctive-inversion-1', nodeId: 'subjunctive-inversion',
    sentence: '___ I known the truth, I would have told you.',
    choices: ['Had', 'If', 'Have', 'Did'], correctIndex: 0,
    explanation: 'if を省略すると倒置が起こる。If I had known → Had I known。',
    sentenceJa: '真実を知っていたら、あなたに話していただろう。', sourceId: AA,
  },
  {
    id: 'pg-subjunctive-inversion-2', nodeId: 'subjunctive-inversion',
    sentence: '___ your help, I could not have finished it.',
    choices: ['Without', 'Unless', 'Except', 'Despite'], correctIndex: 0,
    explanation: 'without / but for は「〜がなければ（なかったら）」で仮定法の条件節に相当する。',
    sentenceJa: 'あなたの助けがなかったら、私はそれを終えられなかっただろう。', sourceId: AA,
  },

  // ---- 疑問詞・疑問文 ----
  {
    id: 'pg-interrogative-basic-1', nodeId: 'interrogative-basic',
    sentence: 'I have no idea ___ to do next.',
    choices: ['what', 'that', 'which of', 'how about'], correctIndex: 0,
    explanation: '〈疑問詞 + to do〉で名詞句を作る。what to do は「何をすべきか」。',
    sentenceJa: '次に何をすべきか見当もつかない。', sourceId: WB,
  },
  {
    id: 'pg-interrogative-basic-2', nodeId: 'interrogative-basic',
    sentence: '___ of these two colors do you prefer?',
    choices: ['Which', 'What', 'Who', 'Whose'], correctIndex: 0,
    explanation: '限られた選択肢から選ばせるときは which。範囲が限定されないときは what。',
    sentenceJa: 'この2色のうちどちらが好きですか。', sourceId: WB,
  },
  {
    id: 'pg-interrogative-indirect-1', nodeId: 'interrogative-indirect',
    sentence: 'Do you know ___ ?',
    choices: ['where he lives', 'where does he live', 'where lives he', 'he lives where'], correctIndex: 0,
    explanation: '間接疑問は〈疑問詞 + 主語 + 動詞〉の平叙文語順になる。',
    sentenceJa: '彼がどこに住んでいるか知っていますか。', sourceId: AA,
  },
  {
    id: 'pg-interrogative-indirect-2', nodeId: 'interrogative-indirect',
    sentence: "You have finished your homework, ___ ?",
    choices: ["haven't you", "didn't you", "don't you", 'have you not so'], correctIndex: 0,
    explanation: '付加疑問は、肯定文には否定形を、直前の助動詞に合わせて作る。',
    sentenceJa: '宿題は終わったよね。', sourceId: PD,
  },
  {
    id: 'pg-interrogative-idiom-1', nodeId: 'interrogative-idiom',
    sentence: '___ if it rains on the day of the trip?',
    choices: ['What', 'How', 'Which', 'Why'], correctIndex: 0,
    explanation: 'What if ~? は「もし〜ならどうなるか」。',
    sentenceJa: '旅行の日に雨が降ったらどうしよう。', sourceId: PD,
  },
  {
    id: 'pg-interrogative-idiom-2', nodeId: 'interrogative-idiom',
    sentence: '___ come you did not tell me about it?',
    choices: ['How', 'What', 'Why', 'Where'], correctIndex: 0,
    explanation: 'How come + 平叙文語順で「どうして〜なのか」。',
    sentenceJa: 'どうしてそのことを話してくれなかったの。', sourceId: PD,
  },

  // ---- 否定 ----
  {
    id: 'pg-negation-scope-1', nodeId: 'negation-scope',
    sentence: 'I did not go out because it was raining. = I stayed home ___ of the rain.',
    choices: ['because', 'in spite', 'instead', 'regardless'], correctIndex: 0,
    explanation: 'not が because 節まで及ぶか本動詞だけかで意味が変わる。ここでは雨が理由。',
    sentenceJa: '雨が降っていたので私は外出しなかった。', sourceId: AA,
  },
  {
    id: 'pg-negation-scope-2', nodeId: 'negation-scope',
    sentence: 'I do not think he ___ come today.',
    choices: ['will', 'will not', 'would not', 'does not'], correctIndex: 0,
    explanation: '英語では否定を主節に繰り上げる。「来ないと思う」は I don\'t think he will come。',
    sentenceJa: '彼は今日来ないと思う。', sourceId: AA,
  },
  {
    id: 'pg-negation-partial-1', nodeId: 'negation-partial',
    sentence: 'The rich are ___ always happy.',
    choices: ['not', 'no', 'never', 'none'], correctIndex: 0,
    explanation: 'not always は「いつも〜とは限らない」という部分否定。',
    sentenceJa: '金持ちがいつも幸せとは限らない。', sourceId: PD,
  },
  {
    id: 'pg-negation-partial-2', nodeId: 'negation-partial',
    sentence: 'He never comes ___ complaining about something.',
    choices: ['without', 'with', 'but', 'unless'], correctIndex: 0,
    explanation: 'never ~ without doing は二重否定で「〜すれば必ず…する」。',
    sentenceJa: '彼は来れば必ず何かに文句を言う。', sourceId: AA,
  },
  {
    id: 'pg-negation-quasi-1', nodeId: 'negation-quasi',
    sentence: 'I can ___ believe what he told me.',
    choices: ['hardly', 'hard', 'almost', 'nearly'], correctIndex: 0,
    explanation: 'hardly は「ほとんど〜ない」という準否定の副詞。hard は「熱心に」。',
    sentenceJa: '彼が私に言ったことはとても信じられない。', sourceId: AA,
  },
  {
    id: 'pg-negation-quasi-2', nodeId: 'negation-quasi',
    sentence: 'His explanation was ___ from satisfactory.',
    choices: ['far', 'free', 'apart', 'much'], correctIndex: 0,
    explanation: 'far from ~ は「決して〜ではない」という強い否定。',
    sentenceJa: '彼の説明は決して満足のいくものではなかった。', sourceId: PD,
  },

  // ---- 話法 ----
  {
    id: 'pg-reported-basic-1', nodeId: 'reported-basic',
    sentence: 'He ___ me that he would come the next day.',
    choices: ['told', 'said', 'said to me that', 'spoke'], correctIndex: 0,
    explanation: 'tell は人を目的語にとる。say は say to me の形にする必要がある。',
    sentenceJa: '彼は翌日来ると私に言った。', sourceId: PD,
  },
  {
    id: 'pg-reported-basic-2', nodeId: 'reported-basic',
    sentence: 'She said, "I saw him yesterday." → She said that she ___ him the day before.',
    choices: ['had seen', 'saw', 'has seen', 'sees'], correctIndex: 0,
    explanation: '間接話法では時制を1つ過去にずらし、yesterday は the day before になる。',
    sentenceJa: '彼女は前日に彼を見たと言った。', sourceId: AA,
  },
  {
    id: 'pg-reported-types-1', nodeId: 'reported-types',
    sentence: 'He asked me ___ I was interested in the job.',
    choices: ['if', 'that', 'what', 'which'], correctIndex: 0,
    explanation: 'Yes/No 疑問文を間接話法にすると if / whether を使う。',
    sentenceJa: '彼は私にその仕事に興味があるか尋ねた。', sourceId: AA,
  },
  {
    id: 'pg-reported-types-2', nodeId: 'reported-types',
    sentence: 'The doctor told me ___ smoking.',
    choices: ['to stop', 'stop', 'that stop', 'stopping'], correctIndex: 0,
    explanation: '命令・依頼の間接話法は〈tell / ask + O + to do〉。',
    sentenceJa: '医者は私に禁煙するように言った。', sourceId: PD,
  },
];
