// System prompts for OpenAI API
// Centralized prompt management for consistency and easy updates

export {
  WORD_EXTRACTION_SYSTEM_PROMPT,
  USER_PROMPT_TEMPLATE,
  WORD_EXTRACTION_WITH_EXAMPLES_SYSTEM_PROMPT,
  USER_PROMPT_WITH_EXAMPLES_TEMPLATE,
} from './prompts/word-extraction';

export {
  CIRCLED_WORD_EXTRACTION_SYSTEM_PROMPT,
  CIRCLED_WORD_USER_PROMPT,
  CIRCLED_WORD_VERIFICATION_SYSTEM_PROMPT,
} from './prompts/circled';

export {
  EIKEN_LEVEL_DESCRIPTIONS,
  getEikenLevelsAbove,
  getEikenFilterInstruction,
  EIKEN_OCR_PROMPT,
  EIKEN_WORD_ANALYSIS_SYSTEM_PROMPT,
  EIKEN_WORD_ANALYSIS_USER_PROMPT,
  EIKEN_SINGLE_PASS_SYSTEM_PROMPT,
  EIKEN_SINGLE_PASS_USER_PROMPT,
} from './prompts/eiken';

export {
  GRAMMAR_OCR_PROMPT,
  GRAMMAR_ANALYSIS_SYSTEM_PROMPT,
  GRAMMAR_ANALYSIS_USER_PROMPT,
  getGrammarLevelFilterInstruction,
} from './prompts/grammar';

export {
  IDIOM_EXTRACTION_SYSTEM_PROMPT,
  IDIOM_USER_PROMPT,
} from './prompts/idiom';

export {
  HIGHLIGHTED_WORD_EXTRACTION_SYSTEM_PROMPT,
  HIGHLIGHTED_WORD_USER_PROMPT,
  HIGHLIGHTED_WORD_VERIFICATION_SYSTEM_PROMPT,
} from './prompts/highlighted';

export {
  WRONG_ANSWER_OCR_SYSTEM_PROMPT,
  WRONG_ANSWER_OCR_USER_PROMPT,
  WRONG_ANSWER_ANALYSIS_SYSTEM_PROMPT,
  WRONG_ANSWER_ANALYSIS_USER_PROMPT,
} from './prompts/wrong-answer';
