-- Link quiz distractors and IPA pronunciation to the shared lexicon master
-- so they can be reused across users instead of being regenerated by AI.
--
-- - pronunciation lives on lexicon_entries (per headword + pos)
-- - distractors live on lexicon_senses (wrong answers are only valid relative
--   to a specific Japanese translation, i.e. a sense)

ALTER TABLE public.lexicon_entries
  ADD COLUMN IF NOT EXISTS pronunciation text NULL;

ALTER TABLE public.lexicon_senses
  ADD COLUMN IF NOT EXISTS distractors jsonb NULL;

-- One-time seed from the existing words corpus. Prefer the newest linked word
-- because generation prompts have improved over time.
WITH pronunciation_seed AS (
  SELECT DISTINCT ON (w.lexicon_entry_id)
    w.lexicon_entry_id,
    btrim(w.pronunciation) AS pronunciation
  FROM public.words AS w
  WHERE w.lexicon_entry_id IS NOT NULL
    AND w.pronunciation IS NOT NULL
    AND btrim(w.pronunciation) <> ''
  ORDER BY w.lexicon_entry_id, w.created_at DESC
)
UPDATE public.lexicon_entries AS le
SET pronunciation = seed.pronunciation
FROM pronunciation_seed AS seed
WHERE le.id = seed.lexicon_entry_id
  AND le.pronunciation IS NULL;

WITH distractor_seed AS (
  SELECT DISTINCT ON (w.lexicon_sense_id)
    w.lexicon_sense_id,
    w.distractors
  FROM public.words AS w
  WHERE w.lexicon_sense_id IS NOT NULL
    AND jsonb_typeof(w.distractors) = 'array'
    AND jsonb_array_length(w.distractors) >= 3
    AND (w.distractors->>0) IS DISTINCT FROM '選択肢1'
  ORDER BY w.lexicon_sense_id, w.created_at DESC
)
UPDATE public.lexicon_senses AS ls
SET distractors = seed.distractors
FROM distractor_seed AS seed
WHERE ls.id = seed.lexicon_sense_id
  AND ls.distractors IS NULL;

-- Expose the new columns through the resolved view (new columns appended so
-- CREATE OR REPLACE keeps existing column positions).
CREATE OR REPLACE VIEW public.lexicon_entry_resolved_rows AS
SELECT
  le.id,
  le.headword,
  le.normalized_headword,
  le.pos,
  le.cefr_level,
  le.dataset_sources,
  ps.id AS primary_sense_id,
  ps.translation_ja,
  ps.normalized_translation_ja,
  ps.meaning_summary,
  ps.usage_notes,
  ps.example_sentence,
  ps.example_sentence_ja,
  ps.translation_source,
  le.created_at,
  le.updated_at,
  ps.distinct_key,
  le.pronunciation,
  ps.distractors
FROM public.lexicon_entries AS le
LEFT JOIN LATERAL (
  SELECT
    ls.id,
    ls.translation_ja,
    ls.normalized_translation_ja,
    ls.distinct_key,
    ls.meaning_summary,
    ls.usage_notes,
    ls.example_sentence,
    ls.example_sentence_ja,
    ls.translation_source,
    ls.distractors
  FROM public.lexicon_senses AS ls
  WHERE ls.lexicon_entry_id = le.id
  ORDER BY ls.is_primary DESC, ls.created_at ASC, ls.id ASC
  LIMIT 1
) AS ps ON true;

-- Recreate the lookup RPC with the new columns (return type changes, so the
-- old function must be dropped first).
DROP FUNCTION IF EXISTS public.get_lexicon_entries_by_keys(jsonb);

CREATE OR REPLACE FUNCTION public.get_lexicon_entries_by_keys(p_keys jsonb)
RETURNS TABLE (
  id uuid,
  headword text,
  normalized_headword text,
  pos text,
  cefr_level text,
  dataset_sources text[],
  primary_sense_id uuid,
  translation_ja text,
  normalized_translation_ja text,
  distinct_key text,
  meaning_summary text,
  usage_notes text,
  translation_source text,
  example_sentence text,
  example_sentence_ja text,
  pronunciation text,
  distractors jsonb,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH input_keys AS (
    SELECT DISTINCT
      nullif(trim(item->>'normalized_headword'), '') AS normalized_headword,
      nullif(trim(item->>'pos'), '') AS pos
    FROM jsonb_array_elements(COALESCE(p_keys, '[]'::jsonb)) AS item
  )
  SELECT
    ler.id,
    ler.headword,
    ler.normalized_headword,
    ler.pos,
    ler.cefr_level,
    ler.dataset_sources,
    ler.primary_sense_id,
    ler.translation_ja,
    ler.normalized_translation_ja,
    ler.distinct_key,
    ler.meaning_summary,
    ler.usage_notes,
    ler.translation_source,
    ler.example_sentence,
    ler.example_sentence_ja,
    ler.pronunciation,
    ler.distractors,
    ler.created_at,
    ler.updated_at
  FROM public.lexicon_entry_resolved_rows AS ler
  INNER JOIN input_keys AS ik
    ON ik.normalized_headword = ler.normalized_headword
   AND ik.pos = ler.pos
  WHERE ik.normalized_headword IS NOT NULL
    AND ik.pos IS NOT NULL;
$$;

REVOKE ALL ON FUNCTION public.get_lexicon_entries_by_keys(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_lexicon_entries_by_keys(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_lexicon_entries_by_keys(jsonb) TO service_role;

-- Nightly backfill from words into the lexicon master, mirroring
-- nightly-lexicon-example-backfill. 04:10 JST = 19:10 UTC (previous day).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM cron.job
    WHERE jobname = 'nightly-lexicon-quiz-content-backfill'
  ) THEN
    PERFORM cron.unschedule('nightly-lexicon-quiz-content-backfill');
  END IF;
END $$;

SELECT cron.schedule(
  'nightly-lexicon-quiz-content-backfill',
  '10 19 * * *',
  $$
  UPDATE public.lexicon_entries AS le
  SET
    pronunciation = btrim(w.pronunciation),
    updated_at = now()
  FROM public.words AS w
  WHERE w.lexicon_entry_id = le.id
    AND le.pronunciation IS NULL
    AND w.pronunciation IS NOT NULL
    AND btrim(w.pronunciation) <> '';

  UPDATE public.lexicon_senses AS ls
  SET
    distractors = w.distractors,
    updated_at = now()
  FROM public.words AS w
  WHERE w.lexicon_sense_id = ls.id
    AND ls.distractors IS NULL
    AND jsonb_typeof(w.distractors) = 'array'
    AND jsonb_array_length(w.distractors) >= 3
    AND (w.distractors->>0) IS DISTINCT FROM '選択肢1';
  $$
);

NOTIFY pgrst, 'reload schema';
